site_name: Example library using mkdocs (mkdocs material, mkdocstrings, mkdocs-gen-files)
site_url: http://localhost:8080/
theme: 
    name: material
plugins: 
    - search 
    - gen-files: 
        scripts: 
            - docs/gen_api_docs.py
    - mkdocstrings
    - section-index
    - literate-nav:
        nav_file: SUMMARY.md
nav: 
    - Code Reference: reference/

markdown_extensions:
- pymdownx.highlight:
    use_pygments: true
    pygments_lang_class: true