site_name: Example library using mkdocs (mkdocs material, mkdocstrings, mkdocs-gen-files)
site_url: http://localhost:8080/
theme: 
    name: material
    features: 
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    palette:
        - scheme: slate
          primary: deep blue
          accent: orange 
          toggle:  
            icon: material/lightbulb-outline
            name: Switch to light mode
        - scheme: default
          primary: blue
          accent: deep orange 
          toggle:  
            icon: material/lightbulb
            name: Switch to dark mode
plugins: 
    - search 
    - gen-files: 
        scripts: 
            - docs/gen_api_docs.py
    - mkdocstrings
    - section-index
    - literate-nav:
        nav_file: SUMMARY.md
nav: 
    - Code Reference: reference/

markdown_extensions:
- pymdownx.highlight:
    # linenums: false -- isn't working
    use_pygments: true
    pygments_lang_class: true
- pymdownx.superfences
- pymdownx.tilde

extra_css: 
    - css/code_select.css