## Source: https://github.com/latk/ganzua/blob/main/.github/actions/setup/action.yaml
name: Set up development tools
description: install Python, UV, and Just
inputs:
  python-version:
    required: true
runs:
  using: composite
  steps:
    - uses: taiki-e/install-action@just
    - uses: actions/setup-python@v5
      with:
        python-version: ${%raw%}{{ inputs.python-version }}{%endraw%}
    - uses: astral-sh/setup-uv
      with:
        enable-cache: true
        python-version: ${%raw%}{{ inputs.python-version }}{%endraw%}