## Source: https://github.com/latk/ganzua/tree/main/.github/workflows
name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:  # allow manual invocation

jobs:
  ci:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: ${%raw%}{{ matrix.python-version }}{%endraw%}
      
      # Keep steps in sync with justfile
      - run: uv sync --locked --all-extras --group dev --group test
      
      - run: just -v lint
      - run: just -v types
      - run: just -v test
      - run: just -v dist