name: Gitleaks Scan
on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
            ${%raw%}{{ secrets.GITHUB_TOKEN }}{%endraw%}
        with:
          args: detect --source . --verbose --redact